### ISSUE TITLE
HELP

### ISSUE THREAD

**Issue by dinhduynhat** [AJS-development/OgarUL-Plugin-Library#39]
i need Video how to install plugins :P please help me :P Shift + mouse right ?

**Comment by LegitSoulja** [comment]
You would use the plugin command, whilst the game is running.

Since you need only a video of how to install plugins then I guess you have already passed the installation phase.

Do search a plugin you can use the command ```plugin search [keyword]``` which the keyboard will be a filter upon searching for a plugin.

You can then install tha plugin by its name **Case Sensitive** using the plugin install command for example ```plugin install MassStart```.

That plugin will then be installed without having to restart. Some plugins needs to be configured for preference before use, which there will be a plugin folder and the plugin names containing in that folder the plugin directory, and configurations and other files.

Good luck

**Comment by LegitSoulja** [comment]
And yes, if you have ogarul dependencies installed then yes. If you go inside the src folder of Ogar-unlimited then **shift + right click** on an empty space inside where files and folders are listed then you can select an option that says **Open command window or prompt here**.

Then, a prompt/console/basic terminal will open and then you would run ogarul simply typing **node index**.

Then whilst the game is loaded, you can use the game ogarul commands using the opened command window which I explained above.

**Comment by dinhduynhat** [comment]
you have the video ? :P i need your facebook :P

**Comment by dinhduynhat** [comment]
![image](https://cloud.githubusercontent.com/assets/20450856/17582370/7a60cc90-5fd5-11e6-8141-f519211c7d41.png)

**Comment by LegitSoulja** [comment]
Um, are you using cigar? Then you can't use these plugins.

**Comment by LegitSoulja** [comment]
And I don't have facebook. My fiancé won't let me, and I won't let her have one lol.

**Comment by LegitSoulja** [comment]
@Agarian close pplease

**Comment by GhostShot3** [comment]
@dinhduynhat You can only use these plugins in OgarUL.
