### ISSUE TITLE
Server Problems

### ISSUE THREAD

**Issue by MatuYT** [AJS-development/OgarUL-Plugin-Library#43]
So.. I was trying to make a server with the Statistics plugin. At least i think that is the plugin i need to make the server, also i have all the plugins expect some bad ones.
I dont know that is wrong with it but the server never goes public... please help me

**Comment by LegitSoulja** [comment]
@MatuYT Do you know exactly what Statistics is used for?

**Comment by MatuYT** [comment]
I just want to make a server to have fun with everybody. And no, i dont. sorry, i'm new to this stuff -.- and please don't start making jokes about me just because im new.

**Comment by LegitSoulja** [comment]
I'd be the last person to joke.

**Comment by LegitSoulja** [comment]
But you don't need **plugins** to run a server, and servers are to better be tanned without plugins, BUT, you can use some plugins you might think will come in handy. You can read the plugin description before downloading.

Since you're new, you should read this https://github.com/AJS-development/Ogar-unlimited/blob/master/README.md
