### ISSUE TITLE
Skin list down??

### ISSUE THREAD

**Issue by ZlkGamingYT** [AJS-development/OgarUL-Plugin-Library#44]
Ok the skin list keeps going down and there is nothing for the new skins!!

**Comment by SharkFinPro** [comment]
I have the skin list - check ur wifi

**Comment by ZlkGamingYT** [comment]
m8 wdym

**Comment by ZlkGamingYT** [comment]
wot m8

**Comment by ZlkGamingYT** [comment]
Shark what do you mean check ur wifi????

**Comment by SharkFinPro** [comment]
boi

**Comment by LegitSoulja** [comment]
The skin list is working. I have disabled cache on the site which was a huge mistake because of the skins loading every time (New) when the page is loaded, or refreshed.

I don't know if that was the cause or not for the skin to not show, but they are working for me. I have tested on 4 different networks, and devices and the skin list is working properly. 

Issue will be closed because there is no issues with skins.
