### ISSUE TITLE
Statistics

### ISSUE THREAD

**Issue by LegitSoulja** [AJS-development/OgarUL-Plugin-Library#6]
Simple plugin for users to use if they want to simply have there server stats stored for a data table view for other people to find new servers and such.

Similar: http://ogar.mivabe.nl/master 
Idea Thought By @EnTerr

Plugin: [Statistics.zip](https://github.com/AJS-development/OgarUL-Plugin-Library/files/265724/Statistics.zip)

Version 1.0.0

In beta, and testing. 

Please note, all servers that are accepted into OgarUl data list will have to be moderated before added. 
When changing your server name, your server name will be changed on the list aswell. 

Your server name can be changed in **index.js**

**Comment by EnTerr** [comment]
As explained in https://github.com/AJS-development/Ogar-unlimited/issues/606 , @EnTerr requests such feature not to be on "opt-in" but "opt-out" basis. That is, not something to be installed or plugged optionally - but the server coming with the batteries included.

**Comment by LegitSoulja** [comment]
@EnTerr beta and testing stage now. Haven't been fully planned if it will a internal thing or not. It would not be a bad idea for external batteries you say.

**Comment by EnTerr** [comment]
Sorry, seems there is some misunderstanding here. Perhaps i should explain: "batteries included" expression comes from Python and means "all that is needed is already included", i.e. you don't need to download and install additional plugins. The meaning here was that the server will be inclined by default to list into the public catalog, unless manually override a flag in the config.

Cue late Grace Hopper: "If it's a good idea, go ahead and do it. It is much easier to apologize than it is to get permission."

**Comment by LegitSoulja** [comment]
@EnTerr it may be, but for now it's a plugin for testing.

**Comment by Andrews54757** [comment]
@EnTerr It would be a opt-in plugin not an opt out plugin for many reasons including privacy

**Comment by EnTerr** [comment]
@Andrews54757, "many"?! - can you tell me 2 more reasons?

**Comment by Andrews54757** [comment]
@EnTerr.

1. A master server could be hacked
2. Not all IPs are port fowarded
3. he might be using DNS
4. Peoples ips contain sensitive material such as location
5. It puts people in risk of hackers as nodejs is not perfect as well
6. Much more I will not explain, you get the idea

**Comment by LegitSoulja** [comment]
@Andrews54757 Yes exactly. Same with what I was talking about

**Comment by EnTerr** [comment]
@Andrews54757:
1. "A master server could be hacked" - so what?! How does this affect the idea of servers self-listing in a catalog? What can an attacker gain from hacking the master, other than getting the already public list of servers? (If someone had flipped the switch "do not publicize" on their server, master knowns nothing about it)
2. "Not all IPs are port fowarded" - sure, so what? Looking at the OgarServ, about 1/4 of servers are not open to connections. Big deal - if can't connect, so try next server!
3. "He might be using DNS" - huh? "Does not compute". If you mean one's IP might be dynamic/unstable and only DynDNS is reliable, that's no big deal because (a) old IP report will expire on master eventually bul also (b) expiration can be improved if server sends a GUID in heartbeat (i.e. server instance generates GUID, when master received same GUID again with new IP, instead of creating new entry, just update old IP)
4. ~~"Peoples ips contain sensitive material such as location"~~ - this is actually not a separate reason but just under "privacy". The mere fact of running a server exposes the IP for geo checks, don't see how catalog furthers concern
5. "It puts people in risk of hackers as nodejs is not perfect as well" - again, how does a catalog worsen the case of one running a server? You cannot host a party without opening the door. Maybe OgUn should be re-written in more secure way (i have no idea what NodeJS issues are) but that's a general issue really
6. ~~Much more I will not explain, you get the idea~~ - :-)) sorry, but this one is just funny

**Comment by Andrews54757** [comment]
@EnTerr 

1. Master server could be hacked - If hacked, it would make the masterserver useless and if they were really good, could hack into other things important such as play.ogarul.tk. Or they could make the MS send requests to all of the servers, effectively freezing all servers through a DDos type attack
2. Not all Ips are port fowarded - It is too much of a hassle to try again. i would rather just click on one and have it work and even if we could make it auto-detect, some networks are faulty
3. He might want to use the DNS address instead so people can remember (such as play.ogarul.tk instead of an ip address)
4. Privacy is a really big issue, so it is valid.
5. Even if we make ogarUl perfect, Nodejs is not. some people are using versions such as 4.0.0 that has security issues
6. There are much more, lets say like how we are going to filter the bad ones

**Comment by Andrews54757** [comment]
@EnTerr The MS was one reason why I stopped using ogarserv.

**Comment by Andrews54757** [comment]
@EnTerr I didnt know about it first and played like normal, but then when looking through gameserver.js, i found a line called masterping and below it saying something like "show our presence to the Master Server" and I looked up the masterserver and was horrified of how they collect your data

**Comment by Andrews54757** [comment]
@EnTerr you know what? i will ask jaralowell about what she thinks about the masterserver

**Comment by Andrews54757** [comment]
https://github.com/JaraLowell/OgarServ/issues/143

**Comment by Andrews54757** [comment]
@LegitSoulja Why do you have to use request for stats? Request is used for getting the html. Rather, why dont you use the POST method instead.

```
sendData(url, c, data) {
var purl = url.parse(url);
     var  options = _.extend(purl, {
method: "POST"
});
    var  r = http.request(options, c); 
   r.write(data);
   r.end()
}
```

**Comment by LegitSoulja** [comment]
@Andrews54757 I didn't even know that existed..

**Comment by LegitSoulja** [comment]
and because on the server side, I was working with get methods, and not post at the time, and used request :/.

**Comment by Andrews54757** [comment]
dont forget to require http by doing `var http = require('http');`. the doc is here: https://nodejs.org/api/http.html

**Comment by LegitSoulja** [comment]
But i'll update it soon, and also finish the stats site. Nobody hasn't use the plugin yet neither

**Comment by LegitSoulja** [comment]
@Andrews54757 And yes, I know about http. I read over that entirely.

**Comment by LegitSoulja** [comment]
@Andrews54757 Here's 1.0.9 update of statistics. You said that you could make it so that people can't edit / cheat with the statistics, so here's the update file. Configuration is still the same.

[stat1.0.9.zip](https://github.com/AJS-development/OgarUL-Plugin-Library/files/324426/stat1.0.9.zip)

**Comment by Andrews54757** [comment]
I have it. Deleting comment

**Comment by Andrews54757** [comment]
@LegitSoulja I created a way. Heres my code. Insert it into your code. Note that I also compacted a lot of your other features down. My code snippet not only checks if it was edited, but also checks for new versions and checks for internet connectivity. https://github.com/Andrews54757/compare/blob/master/fileprotector.js

**Comment by LegitSoulja** [comment]
@Andrews54757 wow, I could've thought of that haha. Thanks.

**Comment by Andrews54757** [comment]
Then I would make a better check.
